name: Python CI - Restaurante Ledger

# ¿Cuándo se ejecuta? Al hacer push a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Variables de entorno "Dummy" para que SQLAlchemy no falle al importar
    env:
      DB_USER: root
      DB_PASSWORD: password_falsa
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: restaurante_test

    steps:
    # 1. Bajar tu código del repositorio
    - uses: actions/checkout@v4

    # 2. Instalar Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    # 3. Instalar tus librerías
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecutar los tests (Solo el básico por ahora)
    - name: Run Sanity Tests
      run: |
        python -m unittest discover tests